config/routes.rb
Rails.application.routes.draw do
  devise_for :members, controllers: { registrations: 'registrations' }
  resources :members, only: [:new, :create, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root to: 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!, only: %i[new create]

  def new
    @post = current_member.posts.build
  end

  def create
    @post = current_member.posts.build(post_params)
    @post.save
    redirect_to root_path
  end

  def index
    @posts = Post.all
    @post = current_member.posts.build if current_member
  end

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:member).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:member).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class ="main-nav">
    <% if member_signed_in? %>
      <h1 class= "title">Hi <%= current_member.name %></h1>
      <%= link_to 'Logout', destroy_member_session_path, method: :delete, class: "button" %>
    <% else %>
      <%= link_to 'Sign In', new_member_session_path, class: "button" %>
      <%= link_to 'Sign Up', new_member_registration_path, class: "button" %>
    <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<h1>blah</h1>

app/views/posts/_form.html.erb
<%= form_for @post, url: {action: "create"}, html: {class: "new-form"} do |f| %>
  <%= f.text_area :body, size: "60x6", class: "text-area" %>
  <br>
  <%= f.submit "Create", class: "create-button" %>
<% end %>

app/views/posts/index.html.erb
<% if member_signed_in? %>
  <%= render 'form'%>
<% end %>
<% @posts.each do |p|%>
  <div class= "posts-area">
    <p><%= p.body%></p>
    <% if member_signed_in? %>
      <h3> <%= p.member.name %> </h3>
    <% else %>
      <h3>anonymous</h3>
    <% end %>
  </div>
  
<% end %>

app/views/posts/new.html.erb
<%= render 'form'%>